<a href="https://colab.research.google.com/github/mohinilodhi/basic-programs/blob/main/Numpy2_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*** important concept of numpy library***




##practice




In [4]:
import numpy as np
a = np.array([2, 3, 4])     ## practice of arithemetic operators
print(a)
print(a * 6)
print(a // 4)
print(a / 4)
print(a * 2)

[2 3 4]
[12 18 24]
[0 0 1]
[0.5  0.75 1.  ]
[4 6 8]


In [6]:
import numpy as np
b = np.array([2, 4, 6])
print(b)
a.size   ##size
a.dtype  ###type



[2 4 6]


dtype('int64')

In [7]:
a.shape #shape

(3,)

In [8]:
a.ndim

1

In [10]:
c = np.array([5, 8, 7])
print(c)

[5 8 7]


In [11]:
c = np.linspace
print(c)

<function linspace at 0x7e4d939f9080>


In [12]:
c = np.zeros(3)
print(c)

[0. 0. 0.]


In [18]:
c = np.ones(7)
print(c)


[1. 1. 1. 1. 1. 1. 1.]


np.float64(1.0)

In [20]:
d = np.array([4, 6, 8 ])
d.sum()



np.int64(18)

In [21]:
d.max()

np.int64(8)

In [22]:
d.min()

np.int64(4)

In [23]:
d.argmax()

np.int64(2)

In [24]:
d.argmin()

np.int64(0)

In [26]:
print(a.dtype.itemsize) # Example: to get itemsize of array 'a'
# If you need to check the total bytes of an array, use a.nbytes
print(a.nbytes) # This would give the total bytes of array 'a'

8
24


In [28]:
d.argmin()

np.int64(0)

In [29]:
d.argsort()

array([0, 1, 2])

In [30]:
d.argmax(axis = 0)

np.int64(2)

In [31]:
d.argmin()

np.int64(0)

In [32]:
d.argmax(axis = 0)

np.int64(2)

In [34]:
d.argmin()

np.int64(0)

In [36]:
## 2 dimensatonal
import numpy as np

p = np.array([[1, 2, 3],[2, 3, 4]])
q = np.array([[2, 4, 5],[5, 6, 8]])
print(p * q)
print(p - q)
print(p / q)


[[ 2  8 15]
 [10 18 32]]
[[-1 -2 -2]
 [-3 -3 -4]]
[[0.5 0.5 0.6]
 [0.4 0.5 0.5]]


In [37]:
p = np.empty(3)

In [40]:
p = p.ravel()

In [41]:
p = np.array([[1, 2, 3], [6, 7, 8]])
print(p.ravel)

<built-in method ravel of numpy.ndarray object at 0x7e4d5d657030>


In [43]:
p.reshape(6, 1)

array([[1],
       [2],
       [3],
       [6],
       [7],
       [8]])

In [45]:
p.nonzero()

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [46]:
import numpy as np
e = np.array([[3, 4, 5],[9, 8, 7],[7, 6, 5]])
print(e)
print

[[3 4 5]
 [9 8 7]
 [7 6 5]]


In [48]:
print(e[2])

[7 6 5]


In [50]:
print(e[1])

[9 8 7]


In [51]:
print(e[0])

[3 4 5]


In [52]:
print(e[1:3])

[[9 8 7]
 [7 6 5]]


In [53]:
print(e[1:2])

[[9 8 7]]


In [54]:
print(e[0:1])

[[3 4 5]]


In [55]:
print(e[-3])

[3 4 5]


In [56]:
print(e[-2])

[9 8 7]


In [57]:
print([-0])

[0]


In [58]:
print(e[-3])

[3 4 5]


In [60]:
import numpy as np
x = np.array ([[1, 2, 3],[5, 6, 7]])

In [61]:
print(x[0, 1])


2


In [62]:
print(x[:,0])

[1 5]


In [64]:
np.argmax(d, axis=0)

np.int64(2)

In [66]:
np.argmin(d)

np.int64(0)