<a href="https://colab.research.google.com/github/mohinilodhi/basic-programs/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#welcome to the numpy tutorial


###array creation: conversion from other python structure


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print(a)


[1 2 3 4 5 6]


In [ ]:
import numpy as np
b = np.array([1, 2, 3, 4, 5, 6])
print(b)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
c = np.array((3, 4, 5, 6, 7))
print(c)

[3 4 5 6 7]


In [ ]:
import numpy as np
d = np.array([[1, 2],[3, 4]])
print(d)


[[1 2]
 [3 4]]


In [ ]:
import numpy as np
e = np.array(range(1, 6))
print(e)

[1 2 3 4 5]


In [ ]:
e.shape

(5,)

In [ ]:
d.shape

(2, 2)

In [ ]:
b.shape

(6,)

In [ ]:
a.shape

(6,)

In [ ]:
c.shape

(5,)

In [ ]:
a.ndim

1

In [ ]:
b.ndim

1

In [ ]:
d.ndim


2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
c.dtype

dtype('int64')

In [ ]:
e.dtype

dtype('int64')

In [ ]:
a.size
b.size
c.size
d.size
e.size

5

In [ ]:
b.size

6

In [ ]:
c.size

5

In [ ]:
d.size

4

In [ ]:
e.size

5

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print(x.ndim)
print(x.size)


(2, 3)
2
6


In [ ]:
np.array([1, 2, 3]) * 3

array([3, 6, 9])

In [ ]:
import numpy as np
array= np.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array = np.ones((2, 6))
print(array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
array = np.empty((2, 4))
print(array)

[[4.64921385e-315 0.00000000e+000 1.39067116e-309 1.10835559e-301]
 [3.48128693e-308 4.54319519e-311 4.21050058e-297 2.13517428e-314]]


In [ ]:
import numpy as np
array = np.arange(1, 2, 23)
print(array)

[1]


In [ ]:
import numpy as np
array = np.linspace(0, 10, 15)
print(array)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [ ]:
import numpy as np
array = np.array([[1, 2, 3],
                  [2, 3, 4],
                  [5, 6, 7,]])
print(array)
array.sum(axis = 0)
array.sum(axis = 1)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


array([ 6,  9, 18])

In [ ]:
array.ndim

2

In [ ]:
array.size


9

In [ ]:
one = np.array([1, 2,3,4, 567,8])
one.argmax()

np.int64(4)

In [ ]:
one.argmin()

np.int64(0)

In [ ]:
one = np.array([1, 2,3, 4,5])
one.argmax()

np.int64(4)

In [ ]:
import numpy as np

arr = np.array([50, 10, 30])

print(np.argsort(arr))

[1 2 0]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
print(result)

[5 7 9]


In [ ]:
import numpy as np

arr = np.array([10, 25, 30, 15])

result = np.where(arr > 20, 1, 0)
print(result)

[0 1 1 0]


In [ ]:
arr = np.array([5, 12, 8, 20])

new_arr = np.where(arr < 10, 100, arr)
print(new_arr)

[100  12 100  20]


In [ ]:
import numpy as np

arr = np.array([0, 5, 0, 8, 3])

print(np.nonzero(arr))

(array([1, 3, 4]),)


In [ ]:
arr = np.array([[1, 0],
                [0, 4]])

print(np.nonzero(arr))

(array([0, 1]), array([0, 1]))


## ***FOR NUMPY PRACTICING ***

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) ##for design and pattern
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[1 2 3 4 5]
(5,)
5
1
int64


In [ ]:
import numpy as np
aar2 = np.array([[1, 2, 3, 4],[2, 3, 4, 5]]) # Corrected to have consistent lengths
print(aar2)
print(aar2.shape)
print(aar2.size)
print(aar2.ndim)
print(aar2.dtype)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)
8
2
int64


In [ ]:
import numpy as np
array = np.array([5, 10, 15, 20])##operators
print(array + 5)
print(array * 2)
print(array ** 2) ###square
print(array[2])

[10 15 20 25]
[10 20 30 40]
[ 25 100 225 400]
15


In [ ]:
import numpy as np
b = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])
c = np.array([[8, 2, 3],
              [6, 3, 4],
              [4, 3, 6]])
print(b[2])## indexing
print(b[1:3])
print(b[-3])
b * c


[4 5 6]
[[2 3 4]
 [4 5 6]]
[1 2 3]


array([[ 8,  4,  9],
       [12,  9, 16],
       [16, 15, 36]])

In [ ]:
import numpy as np
x = np.array ([[1, 2],[3, 4]])
print(x[0, 1])
print(x[1])
print(x[:,0])
x.shape
x.size
x.ndim
x.dtype
x[1, 0:2]

2
[3 4]
[1 3]


array([3, 4])

In [ ]:
import numpy as np
a = np.array([10, 20, 30, 40])
print(a)
# Removed problematic lines: print(a[0,2]) and print(a[-2,1]) as 'a' is 1-dimensional.
print(a * 2)
print(a ** 3)
print(a[0])
a.shape
a.size
a.dtype
a.ndim

b = np.arange(1, 11)
print(b)
c = np.linspace(0, 10, 5)
print(c)
d = np.zeros(6)
print(d)
e = np.ones(6)
print(e)

[10 20 30 40]
[20 40 60 80]
[ 1000  8000 27000 64000]
10
[ 1  2  3  4  5  6  7  8  9 10]
[ 0.   2.5  5.   7.5 10. ]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
a = np.array([10, 20, 30, 5, 7, 1])
np.argmax(a)
a.reshape


<function ndarray.reshape>

In [ ]:
np.argmin(a)

np.int64(5)

In [ ]:
import numpy as np
c = np.array([[1, 2, 3, 4],[2, 3, 4, 5]])
print(c)
np.argmax(c)

[[1 2 3 4]
 [2 3 4 5]]


np.int64(7)

In [ ]:
np.argmin(c)

np.int64(0)

In [ ]:
np.argmax(c, axis=0)

array([1, 1, 1, 1])

In [ ]:
np.argmax(c, axis=1)

array([3, 3])

In [ ]:
np.argmin(c, axis=0)

array([0, 0, 0, 0])

In [ ]:
np.argmin(c, axis=0)

array([0, 0, 0, 0])

In [ ]:
import numpy as np
y = np.array([10, 20, 30, 40, 50, 60, 70])
print(y.reshape(7, 1))

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(12,1))
print(a.reshape(3,4))
print(a.reshape(4,3))


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b = np.array([[5, 1, 9],
              [3, 8, 2]])
np.argmax(b)

np.int64(2)

In [ ]:
np.argmax(b, axis=0)

array([0, 1, 0])

In [ ]:
np.argmax(b, axis =1)

array([2, 1])

In [ ]:
import numpy as np
c = np.array([[4,7,1],
             [9,8,6],
             [3,8,5]])
np.argmin(c)

np.int64(2)

In [ ]:
np.argmin(c, axis=0)

array([2, 0, 0])

In [ ]:
np.argmin(c, axis=1)

array([2, 2, 0])

In [ ]:
import numpy as np
c = np.array([[3, 8],
              [5, 1]])
np.argmax(c)

np.int64(1)

In [ ]:
np.argmax(c, axis=0)

array([1, 0])

In [ ]:
np.argmin(c, axis=1)

array([0, 1])

In [ ]:
import numpy as np
a = np.array([1, 2,3,])
a.size
a.shape
a.ndim
a.dtype
np.argmax(a)
np.argmin(a)
print(a ** 2)
print(a * 3)
print(a / 2)

[1 4 9]
[3 6 9]
[0.5 1.  1.5]


In [ ]:
a.size
a.shape
a.ndim
a.dtype

dtype('int64')

In [ ]:
a.size

3

In [ ]:
a.shape

(3,)

In [ ]:
a.ndim

1

In [ ]:
print(a ** 2)

[1 4 9]


In [ ]:
import numpy as np

array1 = np.array([[1, 2, 3,],
                   [2, 3, 4,]])
array2 = np.array([[2, 3, 4],
                   [2,3 ,7]])

result = array1 + array2 # Assuming addition was the intended operation
print(result.sum(axis = 0))
print(result.sum(axis = 1))

[ 7 11 18]
[15 21]


In [ ]:
b = np.arange(1, 12)
print(b)
c = np.linspace(0, 10, 5)
print(c)
d = np.zeros(9)
print(d)
e = np.ones(12)
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 0.   2.5  5.   7.5 10. ]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
a = np.array([10, 20, 30 , 40, 50, 60])
np.argmax(a)
a.reshape(3, 2)

array([[10, 20],
       [30, 40],
       [50, 60]])